Feat/blake3 u4 input compact representation
BitVM/BitVM pull request #165
Opened 2024-12-23 17:11 UTC by mukeshdroid

The current blake3_u4 has a limitation that only messages of upto 288 bytes could be hashed. blake3_u4_compact overcomes this limitation by packing nibbles into limbs of u32 until they need to be processed. 

Although there is slight increase in the script size, now larger messages (upto 1024 bytes) can be hashed at once leading to savings in both script size and max stack use when computing hash for Fp6 or Fp12 elements.

2024-12-31 17:07 UTC, AaronFeickert requested changes

2024-12-31 17:07 UTC, AaronFeickert commented on src/hash/blake3_official_test_vectors.json
Would recommend including a comment in this file giving a link to its source.

2024-12-31 17:07 UTC, AaronFeickert commented on src/hash/blake3_u4_compact.rs
> +            }
I assume it was checked that this conditional is actually triggered, and that relevant equality checks are really being done?

2024-12-31 17:07 UTC, AaronFeickert commented on src/bigint/std.rs
> +    pub fn pack_limbs<const WINDOW : u32>() -> Script {
Missing documentation.

2024-12-31 17:07 UTC, AaronFeickert commented on src/bigint/std.rs
> +    pub fn unpack_limbs<const WINDOW: u32>() -> Script {
Missing documentation.

2024-12-31 17:07 UTC, AaronFeickert commented on src/hash/blake3_u4_compact.rs
> +pub fn blake3_u4_compact(
Missing documentation.

2025-01-01 06:12 UTC, mukeshdroid commented on src/hash/blake3_official_test_vectors.json
Would It make sense to add the link as a comment when we import it rather than to this file directly. That would make it easier to verify the integrity of this file by comparing its hash with the one found at https://github.com/BLAKE3-team/BLAKE3/blob/master/test_vectors/test_vectors.json .

2025-01-01 09:48 UTC, mukeshdroid commented on src/hash/blake3_u4_compact.rs
> +            }
yes. I have added tests for cases where it should panic.

2025-01-02 22:15 UTC, AaronFeickert commented on src/hash/blake3_official_test_vectors.json
Good call!

2025-01-07 21:22 UTC, AaronFeickert commented on src/hash/blake3_u4_compact.rs
> +            res.push_str(&"0".repeat((64 - (len_bytes % 64)) * 2)); //zero should be added as padding but this is done intentionally to test if blake3_u4_compact can handle wrong padding
Isn't this doing correct padding, not incorrect padding as suggested by the comment?

2025-01-07 21:56 UTC, AaronFeickert commented on src/hash/blake3_u4_compact.rs
Can you ensure that test module function-level comments appear before the `#[test]` attribute? Apparently the formatter doesn't have a default style for this, but I think it makes intent more clear. And selfishly, my editor makes it [more difficult](https://github.com/zed-industries/zed/issues/22798) to run tests otherwise!

2025-01-09 18:44 UTC, AaronFeickert commented
After discussion, a few notes and ideas for this implementation:
- Avoid the use of `U254`-based packing and unpacking functionality. While these work with the full 256 bits we need for BLAKE3 processing, this approach makes the intent unclear and seems very brittle to future changes to `BigIntImpl`.
- Add fuzz testing. This may necessitate different input handling, since the implementation currently panics on invalid input length.
- Refactor (as feasible) to avoid hex/byte conversions. These conversions occur several times and add complexity. While hex representations can make sense for input or output processing, we should stick with byte representations internally as much as possible.
- Check test outputs off the stack. Right now, test vector expected outputs are pushed to the stack as nibbles and compared to the nibbles of the implementation output. This has a bad code smell, since it relies on packing and script functionality to operate as expected. A more robust approach would be to extract the implementation output and check it against the test vector output off the stack.

2025-01-24 13:43 UTC, manishbista28 commented
looks good to me

2025-01-24 17:01 UTC, AaronFeickert requested changes

2025-01-24 17:01 UTC, AaronFeickert commented on bitvm/src/hash/blake3_u4_compact.rs
> +            res.push_str(&"0".repeat((64 - (len_bytes % 64)) * 2)); //zero should be added as padding but this is done intentionally to test if blake3_u4_compact can handle wrong padding
This comment seems incorrect; you are adding zero values.

2025-01-24 18:33 UTC, AaronFeickert commented
I noticed a lot of `println!` output during fuzz testing that makes it difficult to monitor the fuzzer's progress. Would recommend either removing/commenting those, or at least making them conditional on a `not(fuzzing)` target.

2025-01-27 08:26 UTC, mukeshdroid commented
The  blake3_u4_compact is a wrapper that utilizes a lot of the inner primitives from blake3_u4. The input format however is U256 ints that are packed into 9 limbs instead of nibbles. 

A Fuzz target has also been incorporated and blake3_u4_compact has been fuzz tested. The setup for fuzz can be utilized to fuzz test other parts of the bitvm repo.

2025-01-27 22:18 UTC, AaronFeickert requested changes

2025-01-27 22:18 UTC, AaronFeickert commented on bitvm/src/hash/blake3_u4_compact.rs
> +    let use_full_table_toogle: bool = random();
Recommend making this a parameter for the function so the caller can control it more directly.

2025-01-27 22:18 UTC, AaronFeickert commented on fuzz/fuzz_targets/blake3.rs
> +    test_blake3_compact_givenbyteslice(&data.0);
If the test function is updated to take the table flag as a parameter, you can update the `Arbitrary` implementation to include it under the control of the fuzzer.

2025-01-27 22:18 UTC, AaronFeickert commented on fuzz/fuzz_targets/blake3.rs
> +use bitvm::hash::blake3_u4_compact::test_blake3_compact_givenbyteslice;
Does this work with `cargo check` for you? Seems like this doesn't play nicely with the target restriction :(

2025-01-27 22:18 UTC, AaronFeickert commented on bitvm/Cargo.toml
> +unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)', 'cfg(fuzzing)'] }
Nit: missing newline.

2025-01-27 22:18 UTC, AaronFeickert commented on bitvm/src/bigint/mod.rs
> +pub type U256 = BigIntImpl<256,29>;
```suggestion
pub type U256 = BigIntImpl<256, 29>;
```

2025-01-27 22:18 UTC, AaronFeickert commented on bitvm/src/hash/blake3_u4_compact.rs
> +/// - If `msg_len` is 0 or greater than 1024 bytes, the function panics with an assertion error.
This now supports empty input.

2025-01-27 22:18 UTC, AaronFeickert commented on bitvm/src/hash/blake3_u4_compact.rs
> +/// can be added as a hardcoded return value.
This now supports empty input.

2025-01-27 22:18 UTC, AaronFeickert commented on bitvm/src/hash/blake3_u4_compact.rs
> +    use_full_tables: bool,
These parameters are not documented.

2025-01-28 18:13 UTC, AaronFeickert requested changes

2025-01-28 18:13 UTC, AaronFeickert commented on bitvm/src/hash/blake3_u4_compact.rs
> +            test_blake3_compact_giveninputhex(add_padding(gen_random_hex_strs(random_size as u32)), random_size as u32, false);
This should pass a `true` flag, no?

2025-01-28 18:13 UTC, AaronFeickert commented on bitvm/src/hash/blake3_u4_compact.rs
> +            // test with full tables
Incorrect comment, since this uses half tables.

2025-01-29 07:01 UTC, mukeshdroid commented on bitvm/src/hash/blake3_u4_compact.rs
> +            test_blake3_compact_giveninputhex(add_padding(gen_random_hex_strs(random_size as u32)), random_size as u32, false);
yes. Good catch. Fixed in 033beee.

2025-01-29 07:02 UTC, mukeshdroid commented on bitvm/src/hash/blake3_u4_compact.rs
> +            // test with full tables
Corrected @ 033beee.

2025-01-29 19:34 UTC, AaronFeickert approved these changes

2025-01-30 15:52 UTC, lucidLuckylee commented
Thanks for the PR @mukeshdroid and thank you for the review @AaronFeickert! Will you work on integrating this into the chunker?

2025-01-30 15:52 UTC, merged